volumes:
  # this is where the data will stored althoug the docker is restart
  fastapi-example-data:
    external: true
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://example_user:secret@db/example
      WAIT_HOSTS: db:5432
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: example_user
      POSTGRES_DB: example
    ports:
      - "15432:5432"
    # /var/lib/postgresql/data is where the data is stored inside the container in default
    # fastapi-example-data is where the whole data mounted
    volumes:
      - fastapi-example-data:/var/lib/postgresql/data
  ghi:
    image: node:lts-bullseye
    command: npm start
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000
